version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/taskmanager
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./react_Assignment
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 